name: myapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - imagenes/Captura.PNG
    - imagenes/Captura1.PNG
    - imagenes/Captura2.PNG
    - imagenes/Captura3.PNG
    - imagenes/Captura4.PNG
    - imagenes/Captura5.PNG
    - imagenes/Captura6.PNG
    - imagenes/Captura7.PNG
    - imagenes/Captura8.PNG
